version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: tu_contraseña_segura
      POSTGRES_DB: myappdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
